In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
arr +1

array([2, 3, 4, 5, 6, 7])

In [5]:
arr-1

array([0, 1, 2, 3, 4, 5])

In [6]:
arr*5

array([ 5, 10, 15, 20, 25, 30])

In [9]:
arr +=1
arr

array([3, 4, 5, 6, 7, 8])

In [12]:
arr+=2
arr

array([ 7,  8,  9, 10, 11, 12])

In [14]:
arr.max()

12

In [16]:
arr.min()

7

In [19]:
arr = np.array([[2,4,5],[6,7,8],[9,3,5]])
arr



array([[2, 4, 5],
       [6, 7, 8],
       [9, 3, 5]])

In [20]:
arr.min(axis = 0)

array([2, 3, 5])

In [21]:
arr.max(axis = 1)

array([5, 8, 9])

In [23]:
arr.sum()

49