In [1]:
import numpy as np

In [5]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[3,2,1],[6,5,4],[9,8,7]])


In [6]:
arr1 + arr2

array([[ 4,  4,  4],
       [10, 10, 10],
       [16, 16, 16]])

In [7]:
arr1.dot(arr2)

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

In [8]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [12]:
arr = np.array([1,2,3,4,5])
arr



array([1, 2, 3, 4, 5])

In [13]:
arr[2:]

array([3, 4, 5])

In [14]:
arr[:3]

array([1, 2, 3])

In [15]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr1[ : , : ]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr1[ :2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr1[1:2, :1]

array([[4]])