In [1]:
import numpy as np 

In [8]:
arr = np.array([[3,6,3,4,],[6,9,8,7],[7,8,2,1]])
arr

array([[3, 6, 3, 4],
       [6, 9, 8, 7],
       [7, 8, 2, 1]])

In [9]:
np.sort(arr,axis=0,kind='mergesort')

array([[3, 6, 2, 1],
       [6, 8, 3, 4],
       [7, 9, 8, 7]])

In [12]:
np.sort(arr,axis=1,kind='heapsort')

array([[3, 3, 4, 6],
       [6, 7, 8, 9],
       [1, 2, 7, 8]])