In [1]:
import numpy as np

In [9]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[4,5,6,7],[6,7,8,9]])


In [7]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2

array([[4, 5, 6, 7],
       [6, 7, 8, 9]])

In [15]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [14]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 4, 5, 6, 7],
       [5, 6, 7, 8, 6, 7, 8, 9]])

In [16]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 3, 4, 4, 5, 6, 7],
       [5, 6, 7, 8, 6, 7, 8, 9]])

In [21]:
arr = np.concatenate((arr1,arr2),axis=1)

In [22]:
np.hsplit(arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[4, 5, 6, 7],
        [6, 7, 8, 9]])]