In [22]:

! pip install numpy 


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [10]:
import numpy as np
lst = [[1,3,5],[2,5,8]]


In [11]:
arr= np.array(lst)
arr

array([[1, 3, 5],
       [2, 5, 8]])

In [12]:
arr.size

6

In [13]:
arr.shape

(2, 3)

In [14]:
arr.ndim

2

In [15]:
type(arr)

numpy.ndarray

In [16]:
arr.dtype

dtype('int64')

In [21]:
zeros = np.zeros((3,1))
zeros

array([[0.],
       [0.],
       [0.]])

In [24]:
ones = np.ones((1,4))
ones

array([[1., 1., 1., 1.]])