In [1]:
import numpy as np

In [2]:
np.random.random((3,3))

array([[0.53535172, 0.1053362 , 0.61475327],
       [0.4688357 , 0.1953872 , 0.6203522 ],
       [0.02635678, 0.42850034, 0.65633962]])

In [16]:
arr = np.random.random((3,4))
arr

array([[0.73769243, 0.11677505, 0.63499647, 0.59471842],
       [0.5395059 , 0.3473441 , 0.98402038, 0.83627503],
       [0.88935241, 0.75382528, 0.60243083, 0.33348844]])

In [4]:
np.random.random()

0.9947277455201258

In [8]:
if np.random.random()>0.5:
   print("hello")
else:
   print("bye")


bye


In [9]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [19]:
arr = np.reshape(arr,(4,3))
arr

array([[0.73769243, 0.11677505, 0.63499647],
       [0.59471842, 0.5395059 , 0.3473441 ],
       [0.98402038, 0.83627503, 0.88935241],
       [0.75382528, 0.60243083, 0.33348844]])

In [20]:
arr.flatten()

array([0.73769243, 0.11677505, 0.63499647, 0.59471842, 0.5395059 ,
       0.3473441 , 0.98402038, 0.83627503, 0.88935241, 0.75382528,
       0.60243083, 0.33348844])